// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateApiClient(arg1) {
  return window['go']['main']['App']['CreateApiClient'](arg1);
}

export function DeleteApiClient() {
  return window['go']['main']['App']['DeleteApiClient']();
}

export function DeleteApiKey(arg1) {
  return window['go']['main']['App']['DeleteApiKey'](arg1);
}

export function GetAllApiKeys() {
  return window['go']['main']['App']['GetAllApiKeys']();
}

export function GetWildberriesData(arg1) {
  return window['go']['main']['App']['GetWildberriesData'](arg1);
}

export function SaveApiKey(arg1, arg2) {
  return window['go']['main']['App']['SaveApiKey'](arg1, arg2);
}
